In [11]:
# 넘파이의 자료형 < dtype
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [2]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [3]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [5]:
x[0] + x[1]

3.0

In [6]:
x = np.array([1, 2, 3] , dtype='U') # 유니코드 문자열
x.dtype

dtype('<U1')

In [7]:
x[0] + x[1]

'12'

In [12]:
# inf 와 NaN
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [13]:
np.log(0)

-inf

In [14]:
np.exp(-np.inf)

0.0

### 배열 생성
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace

In [16]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [17]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [19]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [20]:
f = np.ones_like(b,dtype="i")
f

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [21]:
g = np.zeros_like(c, dtype="f")
g

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [23]:
# empty ; 배열을 생성만 하고 특정한 값으로 초기화를 안함 > 빠름
h = np.empty((4,3))
h

array([[1.05480606e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.64233733e-067],
       [7.43219968e-091, 3.73455103e-061, 2.34023344e-057],
       [1.42320985e+160, 6.48224659e+170, 4.93432906e+257]])

In [28]:
# arange() ; NumPy버전의 range 명령 (특정한 규칙에 따라 증가하는 수열)
np.arange(10) # 0 ,..., n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(3, 21, 3) # 시작, 끝(포함안함), 간격

array([ 3,  6,  9, 12, 15, 18])

In [32]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수 > 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할함.

array([  0.,  25.,  50.,  75., 100.])

In [31]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [35]:
# 전치 .T
ab = np.array([[1,2,3], [4,5,6], [7,8,9]])
ab

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ab.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
ab = np.arange(12)
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
abx = ab.reshape(3, 4) # 딱맞게 계산 못하겠으면 reshape(3, -1)
abx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
abx2 = ab.reshape(3, -1)
abx2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
# 다차원배열 > 1차원으로 만들기 ; flatten(), ravel()
abx.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
abx.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 배열 연결
행,열의 수가 같은 두 개 이상의 배열을 연결(concatenate) 하여 더 큰 배열을 만듦
- hstack ; 행의 수가 같은 두 개 이상의 배열을 옆으로 연결 (열의 수가 늘어남)
- vstack ; 열의 수가 같은 두 개 이상의 배열을 옆으로 연결 (행의 수가 늘어남)
- dstack ; 깊이 방향으로 배열을 합침.
- stack
- r_
- c_
- tile ; 동일한 배열을 반복하여 연결.

In [48]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
a2 = np.zeros((2,1))
a2

array([[0.],
       [0.]])

In [50]:
np.hstack([a1, a2])

array([[1., 1., 1., 0.],
       [1., 1., 1., 0.]])

In [52]:
b1 = np.ones((3,2))
b1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
b2 = np.zeros((5,2))
b2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
np.vstack([b1, b2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
c1 = np.ones((3,5))
c1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
c2 = np.zeros((3,5))
c2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [68]:
a = np.array([[0,1,2], [3,4,5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [69]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [71]:
# todo ; array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

IndentationError: unexpected indent (<ipython-input-71-08abb9ba0f29>, line 2)

In [78]:
# 2차원 그리드 포인트 생성 (x,y)
x = np.arange(3)
x

array([0, 1, 2])

In [73]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [74]:
X, Y = np.meshgrid(x, y)

In [75]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [76]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [77]:
[list(zip(x, y)) for x, y in zip(X, Y)] 

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]