In [1]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([4,2,2,4])

In [2]:
np.all(a==b)

False

In [3]:
np.all(b==c)

True

In [4]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [5]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [6]:
np.log(a +1)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [7]:
aa = np.array([0,1,2,9])
aa

array([0, 1, 2, 9])

In [8]:
np.log(aa+1)

array([0.        , 0.69314718, 1.09861229, 2.30258509])

In [9]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 넘파이에서는 서로 다른 크기를 가진 두 배열의 사칙연산도 가능. > '브로드캐스팅' 
- 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

In [11]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [13]:
x + 1  # [0,1,2,3,4] + [1,1,1,1,1]

array([1, 2, 3, 4, 5])

In [16]:
m = np.vstack([range(7)[i:i + 3] for i in range(5)])
m

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [20]:
l = np.arange(5)[:, np.newaxis]
l

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
m + l

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

#### 차원축소 연산
- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

In [23]:
a = np.array([[1,2,3,4],[4,2,2,4],[4,2,2,4],[4,2,2,4]])

In [24]:
a

array([[1, 2, 3, 4],
       [4, 2, 2, 4],
       [4, 2, 2, 4],
       [4, 2, 2, 4]])

In [25]:
a.mean()

2.875

In [27]:
a.mean(axis=0) # 열합계

array([3.25, 2.  , 2.25, 4.  ])

In [28]:
a.mean(axis=1) # 행합계

array([2.5, 3. , 3. , 3. ])

### 정렬

In [31]:
s = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
s

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [32]:
np.sort(s)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [33]:
np.sort(s, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [34]:
np.sort(s, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [35]:
np.sort(s, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [36]:
s

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [37]:
sor = np.argsort(s) # 자료의 순서만 알고싶을때
sor

array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)