#### 난수(random number) > Numpy의 random 서브패키지에서 제공
- rand() : 0부터 1사이의 균일 분포
- randn() : 표준 정규 분포
- randint() : 균일 분포의 정수 난수

In [1]:
np.random.seed(0)

In [3]:
np.random.rand(10) # rand() ; 0과 1사이의 난수를 발생시키는 함수

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [6]:
np.random.rand(10)

array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x)
x

array([1, 2, 0, 7, 5, 6, 8, 3, 4, 9])

In [30]:
np.random.randint(10, 20, size=(3,10))

array([[19, 11, 16, 18, 18, 13, 12, 13, 16, 13],
       [16, 15, 17, 10, 18, 14, 16, 15, 18, 12],
       [13, 19, 17, 15, 13, 14, 15, 13, 13, 17]])

#### 데이터샘플링
- choice()

In [26]:
np.random.choice(5, 3, p=[0.0, 0, 0.0, 0.1, 0.9]) # p ; 각 수의 선택확률(합 = 1)

array([4, 4, 4])

In [17]:
np.random.choice(5, 5, replace=False) # like shuffle()

array([3, 0, 1, 4, 2])

In [22]:
np.random.choice(5, 10)

array([0, 0, 3, 2, 3, 0, 4, 0, 0, 2])

#### 정수 데이터 카운팅
- unique ; unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다
- bincount ; bincount 함수는 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 한다. 데이터가 없을 경우에는 카운트 값이 0이 된다

In [48]:
# help(np.unique)

In [32]:
np.unique([11, 11, 13, 15, 2, 5, 2])

array([ 2,  5, 11, 13, 15])

In [39]:
a = np.array([11, 11, 13, 15, 2, 5, 2])
val, cnt = np.unique(a, return_counts=True)

In [40]:
val

array([ 2,  5, 11, 13, 15])

In [45]:
cnt

array([2, 1, 2, 1, 1], dtype=int64)

In [44]:
x = np.repeat(val, cnt)
x

array([ 2,  2,  5, 11, 11, 13, 15])

In [47]:
np.bincount(x, minlength=20)

array([0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0],
      dtype=int64)