### 2장. numpy로 공부하는 선형대수

$ \alpha , \beta , \gamma , \delta , \epsilon , \zeta , \eta , \theta , \kappa , \lambda , \mu , \nu , \xi , \pi , \rho , \sigma , \tau , \phi , \chi , \psi , \omega $

### 2.1 데이터와 행렬

In [7]:
# 1차원 벡터로 표현
x1 = np.array([5.1, 5.2, 5.3])
x1

array([5.1, 5.2, 5.3])

In [8]:
# 2차원 벡터로 표현
x2 = np.array([[5.1], [3.3], [2.2], [1.1]])
x2

array([[5.1],
       [3.3],
       [2.2],
       [1.1]])

In [70]:
# 2.1.1 붓꽃 데이터 x2에 대한 벡터 변수 X2 만들기
from sklearn.datasets import load_iris

X2 = iris.data[1, ]
X2

array([4.9, 3. , 1.4, 0.2])

In [17]:
from sklearn.datasets import load_digits

digits = load_digits() # 데이터 로드
samples = [0, 10, 20, 30, 1, 11, 21, 31] # 선택된 이미지 번호

In [59]:
# 행렬로 표기
x2 = np.array([[1.1, 2.2, 3.3, 4.4], [5.5, 6.6, 7.7, 8.8]])
x2

array([[1.1, 2.2, 3.3, 4.4],
       [5.5, 6.6, 7.7, 8.8]])

In [32]:
A2 = np.ndarray((2,4))

In [53]:
A2 = iris.data[0:2, :]

In [54]:
A2

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [38]:
type(A2)

numpy.ndarray

In [60]:
A = np.array([[11, 21], [12, 22], [13,23]])
A

array([[11, 21],
       [12, 22],
       [13, 23]])

In [62]:
A.shape

(3, 2)

In [63]:
A.T

array([[11, 12, 13],
       [21, 22, 23]])

In [64]:
B = np.array([11, 12, 13])

In [65]:
B

array([11, 12, 13])

In [67]:
# 1차원 ndarray는 전치연산 불가능
B.T

array([11, 12, 13])

In [74]:
# 2.1.3 1) 붓꽃 데이터 X의 전치행렬 구하기

X = iris.data[0:10]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [75]:
X.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1],
       [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1]])

In [76]:
X.shape

(10, 4)

In [77]:
X.T.shape

(4, 10)

In [78]:
# 2.1.3 2) XT를 다시 전치한 행렬 구하기
X.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [80]:
# 위 행렬 비교
(X == X.T.T).all()

True

In [82]:
# 영벡터
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [83]:
# 일벡터
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [86]:
# 대각 정방행렬 (대각 빼고 다 0인 행렬)
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [91]:
# 항등행렬 (대각성분이 모두 1)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
X2 = np.diag([2,3,4])
X2

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [95]:
X2.T

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [99]:
# 대칭행렬 ; 원행렬 == 전치행렬 
(X2 == X2.T).all()

True

In [105]:
# 2.1.4 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예 만들기 & 벡터와 행렬을 넘파이로 나타내기
one = np.zeros(4)
one

array([0., 0., 0., 0.])

In [106]:
two = np.ones(4)
two

array([1., 1., 1., 1.])

In [108]:
three = np.eye(5)
three

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [110]:
four = np.diag([2,3,4,5,6])
four

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [111]:
five = np.identity(4)
five

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
m_1 = np.arange(9).reshape(3, 3)
m_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
# 대칭행렬
m = m_1 + m_1.T
m

array([[ 0,  4,  8],
       [ 4,  8, 12],
       [ 8, 12, 16]])

### 2.2 벡터와 행렬의 연산