#### 배열 ; 적은 메모리롤 많은 데이터를 빠르게 처리가능 > 파이썬에서는 NumPy 이용해서 배열 다뤄야함
- 모든 원소가 같은 자료형 & 원소 갯수 못바꿈
- 다차원의 배열 자료구조 클래스인 `ndarray` 클래스 지원
- 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용됨

In [41]:
ar = np.array([1,2,3,4,5,6,7,8,9])
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
type(ar)

numpy.ndarray

In [45]:
ar * 2 
# 리스트였다면, 반복문 사용했어야함

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
L = [1,2,3,4,5,6,7,8,9]
L * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [49]:
2 * a + b

array([12, 24, 36])

In [50]:
a == 2

array([False,  True, False])

In [51]:
b > 10

array([False,  True,  True])

In [52]:
(a == 2) & (b > 10)

array([False,  True, False])

In [54]:
# 2차원배열 (=행렬(matrix))
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
# 행의 갯수
len(c)

2

In [58]:
# 열의 갯수
len(c[0])

3

In [59]:
# 연습문제
ex = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
ex

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [66]:
# 3차원 배열 (면, 행, 열)
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) 

In [67]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [68]:
# 면 , 행 , 열
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [70]:
# 배열의 차원과 속성 알아내기
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [71]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [72]:
c[0,2]

2

In [73]:
c[1,2]

5

In [74]:
c[-1, -1]

5

In [75]:
# 배열 슬라이싱 ; 슬라이싱과 comma 함께 사용하면 됨.

In [82]:
c[0, :] # 1번째 행 전체

array([0, 1, 2])

In [84]:
c[:, 1] # 2번째 열 전체

array([1, 4])

In [87]:
c[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([4, 5])

In [86]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
c[:2, :2]

array([[0, 1],
       [3, 4]])

In [89]:
# 연습문제
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [90]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
m[1, 2]

7

In [92]:
m[2,-1]

14

In [93]:
m[1,1:3]

array([6, 7])

In [94]:
m[1:, 2]

array([ 7, 12])

In [95]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [96]:
# 배열 인덱싱
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [98]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [99]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [100]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [102]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx] # 홀수번째 원소만 골라내기

array([11, 33, 55, 77, 99])

In [105]:
ab = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ab

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
ab[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [108]:
ab[[2,0,1] , :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [109]:
# 연습문제
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [110]:
# 3의 배수 찾기
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [111]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [112]:
x[(x%3==0) & (x%4==1)]

array([9])